language: node_js

node_js:
  - "6"
  - "7"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

env:
  global:
    - FANART_API_KEY=d9e25d5beda1027a1674c1585882309e
    - THEAUDIODB_API_KEY=1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - yarn test

after_success:
  - $(yarn bin)/nyc report --reporter=text-lcov | $(yarn bin)/coveralls
  - bash <(curl -s https://codecov.io/bash)
