language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - yarn test

after_success:
  - $(yarn bin)/nyc report --reporter=text-lcov | $(yarn bin)/coveralls
  - bash <(curl -s https://codecov.io/bash)
